version: 4.2
os: linux
files:
  - source: /
    destination: /opt/fit2cloud-plugin2.0-test/
hooks:
  ApplicationStop:
    - location: win_scripts/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: win_scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: win_scripts/configure.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: win_scripts/start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: win_scripts/validate_service.sh
      timeout: 300
      runas: root
